---
- name: "ssl_exporter | Include packages tasks [for deps]"
  ansible.builtin.import_tasks:
    file: "packages.yml"
  vars:
    ssl_exporter_pacakges_variant: "{{ lookup('ansible.builtin.vars',
      'ssl_exporter_packages_deps') }}"
- name: "ssl_exporter | Download & unarchive exporter binary from tarball"
  ansible.builtin.unarchive:
    src: "{{ lookup('ansible.builtin.vars', 'ssl_exporter_url') + '/v' +
      lookup('ansible.builtin.vars', 'ssl_exporter_version') +
      '/ssl_exporter_' + lookup('ansible.builtin.vars',
      'ssl_exporter_version') + '_' + lookup('ansible.builtin.vars',
      'ssl_exporter_arch') + '.tar.gz' }}"
    dest: "{{ lookup('ansible.builtin.vars', 'ssl_exporter_dest') }}"
    remote_src: "yes"
<<<<<<< Updated upstream
    include: "{{ 'ssl_exporter-' + lookup('ansible.builtin.vars',
      'ssl_exporter_version') + '.' + lookup('ansible.builtin.vars',
      'ssl_exporter_arch') + '/ssl_exporter' }}"
=======
    include: "ssl_exporter"
>>>>>>> Stashed changes
    mode: "0775"
    owner: "root"
    group: "root"
